// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePluginPermissions(arg1, arg2) {
  return window['go']['service']['App']['ApprovePluginPermissions'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['service']['App']['CancelDownload'](arg1);
}

export function CheckPluginChain(arg1) {
  return window['go']['service']['App']['CheckPluginChain'](arg1);
}

export function CreateAccount(arg1, arg2) {
  return window['go']['service']['App']['CreateAccount'](arg1, arg2);
}

export function CreateTemplate(arg1) {
  return window['go']['service']['App']['CreateTemplate'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['service']['App']['DeleteAccount'](arg1);
}

export function DeletePluginConfig(arg1) {
  return window['go']['service']['App']['DeletePluginConfig'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['service']['App']['DeleteTemplate'](arg1);
}

export function ExecutePluginRoute(arg1, arg2, arg3) {
  return window['go']['service']['App']['ExecutePluginRoute'](arg1, arg2, arg3);
}

export function ExecuteRouteForAccount(arg1, arg2, arg3) {
  return window['go']['service']['App']['ExecuteRouteForAccount'](arg1, arg2, arg3);
}

export function GetALLLang() {
  return window['go']['service']['App']['GetALLLang']();
}

export function GetAccount(arg1) {
  return window['go']['service']['App']['GetAccount'](arg1);
}

export function GetAccountConfig(arg1) {
  return window['go']['service']['App']['GetAccountConfig'](arg1);
}

export function GetAccountCredentials(arg1) {
  return window['go']['service']['App']['GetAccountCredentials'](arg1);
}

export function GetAllPluginConfigs() {
  return window['go']['service']['App']['GetAllPluginConfigs']();
}

export function GetCurrentLang() {
  return window['go']['service']['App']['GetCurrentLang']();
}

export function GetDeveloperMode() {
  return window['go']['service']['App']['GetDeveloperMode']();
}

export function GetDownloadStatus(arg1) {
  return window['go']['service']['App']['GetDownloadStatus'](arg1);
}

export function GetDownloaderConfig() {
  return window['go']['service']['App']['GetDownloaderConfig']();
}

export function GetEngineVersions() {
  return window['go']['service']['App']['GetEngineVersions']();
}

export function GetInstalledPlugins() {
  return window['go']['service']['App']['GetInstalledPlugins']();
}

export function GetLangPack() {
  return window['go']['service']['App']['GetLangPack']();
}

export function GetLangTextMap() {
  return window['go']['service']['App']['GetLangTextMap']();
}

export function GetLogFileContent(arg1) {
  return window['go']['service']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['service']['App']['GetLogFiles']();
}

export function GetLogLevel() {
  return window['go']['service']['App']['GetLogLevel']();
}

export function GetMarketPlugins() {
  return window['go']['service']['App']['GetMarketPlugins']();
}

export function GetPluginApprovedPermissions(arg1) {
  return window['go']['service']['App']['GetPluginApprovedPermissions'](arg1);
}

export function GetPluginChain(arg1) {
  return window['go']['service']['App']['GetPluginChain'](arg1);
}

export function GetPluginConfig(arg1) {
  return window['go']['service']['App']['GetPluginConfig'](arg1);
}

export function GetPluginPermissions(arg1) {
  return window['go']['service']['App']['GetPluginPermissions'](arg1);
}

export function GetPlugins() {
  return window['go']['service']['App']['GetPlugins']();
}

export function GetProcessName() {
  return window['go']['service']['App']['GetProcessName']();
}

export function GetSystemInfo() {
  return window['go']['service']['App']['GetSystemInfo']();
}

export function GetTemplate(arg1) {
  return window['go']['service']['App']['GetTemplate'](arg1);
}

export function GetTemplateCapabilities(arg1) {
  return window['go']['service']['App']['GetTemplateCapabilities'](arg1);
}

export function InstallPluginFromMarket(arg1) {
  return window['go']['service']['App']['InstallPluginFromMarket'](arg1);
}

export function IsPluginPermissionApproved(arg1, arg2) {
  return window['go']['service']['App']['IsPluginPermissionApproved'](arg1, arg2);
}

export function ListAccountsByTemplate(arg1) {
  return window['go']['service']['App']['ListAccountsByTemplate'](arg1);
}

export function ListDownloads() {
  return window['go']['service']['App']['ListDownloads']();
}

export function ListLocalFiles(arg1, arg2) {
  return window['go']['service']['App']['ListLocalFiles'](arg1, arg2);
}

export function ListTemplates() {
  return window['go']['service']['App']['ListTemplates']();
}

export function OpenLocalFile(arg1, arg2) {
  return window['go']['service']['App']['OpenLocalFile'](arg1, arg2);
}

export function PauseDownload(arg1) {
  return window['go']['service']['App']['PauseDownload'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['service']['App']['ReadFileContent'](arg1);
}

export function RecordPluginInstall(arg1, arg2, arg3) {
  return window['go']['service']['App']['RecordPluginInstall'](arg1, arg2, arg3);
}

export function ReloadPlugins() {
  return window['go']['service']['App']['ReloadPlugins']();
}

export function RemoveDownload(arg1) {
  return window['go']['service']['App']['RemoveDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['service']['App']['ResumeDownload'](arg1);
}

export function RevokeAllPluginPermissions(arg1) {
  return window['go']['service']['App']['RevokeAllPluginPermissions'](arg1);
}

export function RevokePluginPermission(arg1, arg2) {
  return window['go']['service']['App']['RevokePluginPermission'](arg1, arg2);
}

export function SetDeveloperMode(arg1) {
  return window['go']['service']['App']['SetDeveloperMode'](arg1);
}

export function SetDownloaderConfig(arg1, arg2, arg3) {
  return window['go']['service']['App']['SetDownloaderConfig'](arg1, arg2, arg3);
}

export function SetLanguage(arg1) {
  return window['go']['service']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['service']['App']['SetLogLevel'](arg1);
}

export function SetPluginChain(arg1, arg2) {
  return window['go']['service']['App']['SetPluginChain'](arg1, arg2);
}

export function SetPluginConfig(arg1, arg2) {
  return window['go']['service']['App']['SetPluginConfig'](arg1, arg2);
}

export function TestPluginWithAccount(arg1, arg2, arg3) {
  return window['go']['service']['App']['TestPluginWithAccount'](arg1, arg2, arg3);
}

export function UninstallPlugin(arg1) {
  return window['go']['service']['App']['UninstallPlugin'](arg1);
}

export function UpdateAccountConfig(arg1, arg2) {
  return window['go']['service']['App']['UpdateAccountConfig'](arg1, arg2);
}

export function UpdateAccountCredentials(arg1, arg2) {
  return window['go']['service']['App']['UpdateAccountCredentials'](arg1, arg2);
}

export function UpdateAccountLocalPath(arg1, arg2) {
  return window['go']['service']['App']['UpdateAccountLocalPath'](arg1, arg2);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['service']['App']['WriteFileContent'](arg1, arg2);
}
