// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {global} from '../models';
import {service} from '../models';
import {engine} from '../models';

export function ApprovePluginPermissions(arg1:string,arg2:Array<string>):Promise<boolean>;

export function CancelDownload(arg1:string):Promise<boolean>;

export function CheckPluginChain(arg1:string):Promise<Array<string>>;

export function CreateAccount(arg1:string,arg2:string):Promise<global.Account>;

export function CreateTemplate(arg1:string):Promise<global.Template>;

export function DeleteAccount(arg1:string):Promise<boolean>;

export function DeletePluginConfig(arg1:string):Promise<boolean>;

export function DeleteTemplate(arg1:string):Promise<boolean>;

export function ExecutePluginRoute(arg1:string,arg2:string,arg3:Record<string, any>):Promise<service.PluginResult>;

export function ExecuteRouteForAccount(arg1:string,arg2:string,arg3:Record<string, any>):Promise<service.PluginResult>;

export function GetALLLang():Promise<Array<global.LanguageInfo>>;

export function GetAccount(arg1:string):Promise<global.Account>;

export function GetAccountConfig(arg1:string):Promise<string>;

export function GetAccountCredentials(arg1:string):Promise<string>;

export function GetAllPluginConfigs():Promise<Record<string, string>>;

export function GetCurrentLang():Promise<string>;

export function GetDeveloperMode():Promise<boolean>;

export function GetDownloadStatus(arg1:string):Promise<engine.TaskStatus>;

export function GetDownloaderConfig():Promise<service.DownloaderConfig>;

export function GetEngineVersions():Promise<service.EngineVersions>;

export function GetInstalledPlugins():Promise<Array<global.InstalledPlugin>>;

export function GetLangPack():Promise<global.LanguagePack>;

export function GetLangTextMap():Promise<Record<string, string>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogLevel():Promise<string>;

export function GetMarketPlugins():Promise<Array<global.MarketPluginInfo>>;

export function GetPluginApprovedPermissions(arg1:string):Promise<Array<string>>;

export function GetPluginChain(arg1:string):Promise<Array<global.PluginChain>>;

export function GetPluginConfig(arg1:string):Promise<string>;

export function GetPluginPermissions(arg1:string):Promise<Array<string>>;

export function GetPlugins():Promise<Array<service.PluginInfo>>;

export function GetProcessName():Promise<string>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function GetTemplate(arg1:string):Promise<global.Template>;

export function GetTemplateCapabilities(arg1:string):Promise<Record<string, boolean>>;

export function InstallPluginFromMarket(arg1:string):Promise<boolean>;

export function IsPluginPermissionApproved(arg1:string,arg2:string):Promise<boolean>;

export function ListAccountsByTemplate(arg1:string):Promise<Array<global.Account>>;

export function ListDownloads():Promise<Array<service.DownloadListItem>>;

export function ListLocalFiles(arg1:string,arg2:string):Promise<service.PluginResult>;

export function ListTemplates():Promise<Array<global.Template>>;

export function OpenLocalFile(arg1:string,arg2:string):Promise<boolean>;

export function PauseDownload(arg1:string):Promise<engine.TaskStatus>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RecordPluginInstall(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function ReloadPlugins():Promise<boolean>;

export function RemoveDownload(arg1:string):Promise<boolean>;

export function ResumeDownload(arg1:string):Promise<string>;

export function RevokeAllPluginPermissions(arg1:string):Promise<boolean>;

export function RevokePluginPermission(arg1:string,arg2:string):Promise<boolean>;

export function SetDeveloperMode(arg1:boolean):Promise<boolean>;

export function SetDownloaderConfig(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function SetLanguage(arg1:string):Promise<boolean>;

export function SetLogLevel(arg1:string):Promise<boolean>;

export function SetPluginChain(arg1:string,arg2:Array<string>):Promise<boolean>;

export function SetPluginConfig(arg1:string,arg2:string):Promise<boolean>;

export function TestPluginWithAccount(arg1:string,arg2:string,arg3:Record<string, any>):Promise<service.PluginResult>;

export function UninstallPlugin(arg1:string):Promise<boolean>;

export function UpdateAccountConfig(arg1:string,arg2:string):Promise<boolean>;

export function UpdateAccountCredentials(arg1:string,arg2:string):Promise<boolean>;

export function UpdateAccountLocalPath(arg1:string,arg2:string):Promise<boolean>;

export function WriteFileContent(arg1:string,arg2:string):Promise<boolean>;
